Добавление redux-middleware and throttle
maksimLyshchik/test-task pull request #13
Opened 2021-08-27 11:30 UTC by maksimLyshchik

2021-08-31 10:11 UTC, papakapa commented on src/App.js
> +  window.onload = () => {
может уместнее будет использование useEffect?

2021-08-31 10:27 UTC, maksimLyshchik commented on src/App.js
> +  window.onload = () => {
да, думаю лучше использовать useEffect, исправил

2021-08-31 10:45 UTC, papakapa approved these changes

2021-08-31 10:45 UTC, papakapa commented on src/App.js
> +
лишняя строка, а так норм

2021-08-31 11:10 UTC, m4eryk commented on src/App.js
> +  window.onload = () => {
А зачем это делать в компоненте?

2021-08-31 11:35 UTC, maksimLyshchik commented on src/App.js
> +  window.onload = () => {
я думал, что компонента загружается и тогда загружается initialState.
Или state должен загружаться независимо от компоненты, как ты показывал, в index?

2021-08-31 19:33 UTC, m4eryk commented on src/App.js
> +  window.onload = () => {
у тебя app уже с initialState

2021-08-31 19:34 UTC, m4eryk commented on src/App.js
> +  window.onload = () => {
Переносить в useEffect корне не верно

2021-08-31 21:21 UTC, m4eryk requested changes

2021-08-31 21:21 UTC, m4eryk commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTask({value: task, id: taskId, timeCreation: Date.now(), status: TODO, timeChange: Date.now()}));
тут уже достаточно много параметров в функции, напиши в столбик

2021-08-31 21:21 UTC, m4eryk commented on src/App.js
> +    Object.values(initialState.tasks).map(task => {
зачем ты делаешь `map`?

2021-09-01 06:31 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTask({value: task, id: taskId, timeCreation: Date.now(), status: TODO, timeChange: Date.now()}));
исправил

2021-09-01 06:33 UTC, maksimLyshchik commented on src/App.js
> +  window.onload = () => {
понял, спасибо

2021-09-01 06:57 UTC, maksimLyshchik commented on src/store/tasks/selectorTasks.js
> +export const selectTasksCount = store => Object.keys(store.tasks).length;
да, нужно использовать. исправил

2021-09-01 07:01 UTC, maksimLyshchik commented on src/store/middleware/loggerMiddleware.js
> +export const loggerMiddleware = store => next => action => {
удалил

2021-09-01 07:03 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +  const taskId = ++tasksCount;
да, наверное вычислять лучше сразу при добавлении

2021-09-01 08:51 UTC, maksimLyshchik commented on src/store/middleware/addDataToLocalStoreMiddleware.js
> +  const setLocalStore = () => localStorage.setItem('store', JSON.stringify(store.getState()));
Вынести setLocalStore в index?

2021-09-01 08:54 UTC, maksimLyshchik commented on src/App.js
> +    Object.values(initialState.tasks).map(task => {
Здесь я перебирал каждую задачу, чтобы добавить её.
Наверное лучше сразу присвоить state = initalState?

2021-09-01 12:04 UTC, papakapa commented on src/App.js
> +    Object.values(initialState.tasks).map(task => {
наверное Саша, имел ввиду что ты юзаешь `map` без присваивания значения другой переменной
если надо было перебрать, то лучше юзать `forEach()`

2021-09-01 12:24 UTC, maksimLyshchik commented on src/App.js
> +    Object.values(initialState.tasks).map(task => {
тогда понял, да в этом случае нужно forEach()

2021-09-02 08:43 UTC, papakapa approved these changes

2021-09-02 21:27 UTC, m4eryk requested changes

2021-09-02 21:27 UTC, m4eryk commented on src/helpers/throttle.js
> +  savedArgs = null,
у нас вроде бесплатные буквы `let` давай их не жалеть)

2021-09-02 21:27 UTC, m4eryk commented on src/helpers/throttle.js
> +        savedArgs = savedThis = null;
это слишком не явно, просто сделает это так
```
savedArgs = null;
savedThis = null;
```

2021-09-02 21:27 UTC, m4eryk commented on src/index.js
> +export const setLocalStore = () => localStorage.setItem('store', JSON.stringify(store.getState()));
не совсем понимаю смысл этих двух строк

2021-09-03 12:53 UTC, maksimLyshchik commented on src/helpers/throttle.js
> +        savedArgs = savedThis = null;
понял, исправил

2021-09-03 12:54 UTC, maksimLyshchik commented on src/helpers/throttle.js
> +  savedArgs = null,
да, точно, бесплатные)
исправил

2021-09-03 13:13 UTC, maksimLyshchik commented on src/index.js
> +export const setLocalStore = () => localStorage.setItem('store', JSON.stringify(store.getState()));
обсудили лично
исправил

2021-09-06 09:05 UTC, m4eryk requested changes

2021-09-06 09:05 UTC, m4eryk commented on src/components/AddTask/AddTask.jsx
> +      id: ++tasksCount,
правильно ли я понимаю что если изначально `tasksCount = 0`, затем после `++tasksCount` он будет равен 1, а потом на 24 строке он будет равен 2? 

Не совсем понимаю зачем мы инкрементируем id задачи

2021-09-06 09:05 UTC, m4eryk commented on src/index.js
> +    store.dispatch(addTask({
store.dispatch(addTask({ ...tasks }))

2021-09-06 09:05 UTC, m4eryk commented on src/store/middleware/addDataToLocalStoreMiddleware.js
> +  const throttleLocalStore = throttle(setLocalStore, 60000);
вынести этот период в константы и jsdoc`ой напиши зачем он такой

2021-09-06 14:19 UTC, papakapa commented on src/helpers/throttle.js
> +      return;
логически отделить

2021-09-07 20:52 UTC, m4eryk commented
@maksimLyshchik есть не исправленные замечания

2021-09-08 06:17 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +      id: ++tasksCount,
Да здесь неправильно работает, в следующем pr исправлено уже

2021-09-08 06:21 UTC, maksimLyshchik commented on src/index.js
> +    store.dispatch(addTask({
да, так лучше, спасибо

2021-09-08 06:22 UTC, maksimLyshchik commented on src/helpers/throttle.js
> +      return;
отделил, спасибо

2021-09-08 06:38 UTC, maksimLyshchik commented on src/store/middleware/addDataToLocalStoreMiddleware.js
> +  const throttleLocalStore = throttle(setLocalStore, 60000);
Хорошо, сделал

2021-09-08 08:00 UTC, merged