Add redux thunk
maksimLyshchik/test-task pull request #15
Opened 2021-09-01 14:50 UTC by maksimLyshchik

2021-09-02 21:28 UTC, m4eryk commented
Нужно поменять бейз ветку мердж реквеста

2021-09-03 13:19 UTC, m4eryk requested changes

2021-09-03 13:19 UTC, m4eryk commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTaskThunkCreator(task, newId));
теперь же можно получать newId  в чанке?

2021-09-03 13:19 UTC, m4eryk commented on src/store/tasks/reducerTasks.js
> +export const addTaskThunkCreator = (task, newId) => (dispatch) => {
ThunkCreator  не нужно добавлять слишком много получается

2021-09-03 13:19 UTC, m4eryk commented on src/store/tasks/reducerTasks.js
> +export const addTaskThunkCreator = (task, newId) => (dispatch) => {
Вынеси каждую чанку в отдельный файл, создай там индекс и делай именованный импорт

2021-09-03 13:19 UTC, m4eryk commented on src/store/tasks/selectorTasks.js
> +export const selectTasksId = createSelector(
да кто так этот ваш TasksId? 

Ты же считаешь тут кол-во)

2021-09-06 06:16 UTC, maksimLyshchik commented on src/store/tasks/selectorTasks.js
> +export const selectTasksId = createSelector(
Почему? здесь я получаю id всех задач, чтобы потом выбрать больший и от него продолжить счёт задач

2021-09-06 07:18 UTC, maksimLyshchik commented on src/store/tasks/reducerTasks.js
> +export const addTaskThunkCreator = (task, newId) => (dispatch) => {
согласен

2021-09-06 07:23 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTaskThunkCreator(task, newId));
да, вено, перенес

2021-09-06 07:27 UTC, maksimLyshchik commented on src/store/tasks/reducerTasks.js
> +export const addTaskThunkCreator = (task, newId) => (dispatch) => {
исправил, но нужно посмотреть

2021-09-06 07:35 UTC, papakapa requested changes

2021-09-06 07:35 UTC, papakapa commented on src/components/EditorTasks/EditorTasks.js
> +    dispatch(collapsingTask(tasks, markTasksId));
можно упростить в одну строку

2021-09-06 07:35 UTC, papakapa commented on src/components/EditorTasks/EditorTasks.js
> +    dispatch(splittingTask(tasks, markTasksId));
тоже самое

2021-09-06 07:42 UTC, maksimLyshchik commented on src/components/EditorTasks/EditorTasks.js
> +    dispatch(collapsingTask(tasks, markTasksId));
согласен, исправил

2021-09-06 07:42 UTC, maksimLyshchik commented on src/components/EditorTasks/EditorTasks.js
> +    dispatch(splittingTask(tasks, markTasksId));
ок, спасибо

2021-09-06 09:10 UTC, m4eryk requested changes

2021-09-06 09:10 UTC, m4eryk commented on src/helpers/getUniqId.js
> +  const maxTaskId = Math.max.apply(Math, tasksId);
а зачем это делать через `apply`

2021-09-06 09:10 UTC, m4eryk commented on src/store/tasks/selectorTasks.js
> +export const selectTasksId = createSelector(
немного странная логика, мы подвязвыаемся на то-что у нас все задачи по порядку - но ок

2021-09-07 20:52 UTC, m4eryk commented
мерджи

2021-09-08 06:41 UTC, maksimLyshchik commented on src/helpers/getUniqId.js
> +  const maxTaskId = Math.max.apply(Math, tasksId);
исправлено в следующем pr

2021-09-08 06:48 UTC, maksimLyshchik commented on src/store/tasks/selectorTasks.js
> +export const selectTasksId = createSelector(
Когда схлопываем и разбиваем схлопнутую задачу удаляется её id  и уже количество id не совпадает с последним(максимальным) полученным id, и при доюавлении новой задачи происходило цикличное перезаписывание последних задач

2021-09-08 06:54 UTC, merged