Search for tasks by value
maksimLyshchik/test-task pull request #16
Opened 2021-09-02 15:29 UTC by maksimLyshchik

2021-09-06 07:54 UTC, papakapa requested changes

2021-09-06 07:54 UTC, papakapa commented on src/components/AddTask/AddTask.jsx
> +      return;
логически отделить `return`

2021-09-06 07:54 UTC, papakapa commented on src/components/SideBarLeft/SearchTasks/SearchTasks.js
> +    if (value.length > 2 || value.length === 0) {
то есть при одном символе, поиск не будет производиться
может есть какая причина для этого?

2021-09-06 07:54 UTC, papakapa commented on src/components/TasksList/TasksList.jsx
> +    return filtredTasks;
логически отделить `return`

2021-09-06 07:55 UTC, papakapa requested changes
если заходить с пустым `localStorage` падает ошибка

2021-09-06 08:00 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +      return;
исправил

2021-09-06 08:01 UTC, maksimLyshchik commented on src/components/SideBarLeft/SearchTasks/SearchTasks.js
> +    if (value.length > 2 || value.length === 0) {
сделано для того чтобы исключить поиск по предлогам. Ищес слова от 3-х символов

2021-09-06 08:01 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    return filtredTasks;
исправил

2021-09-06 08:56 UTC, m4eryk requested changes

2021-09-06 08:56 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +      return filtredTasks.filter(task => task.value.toLowerCase().indexOf(valueSearch.toLowerCase()) > -1);
тут на сколько я понимаю получается сложность On^2, такие функции нужно мемофицировать

2021-09-06 08:56 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +  const sortedTasks = searchTasks().sort((itemPrev, itemPres) => {
sort имеет изначально не линейную сложность и такое точно нужно мемофицировать

2021-09-06 08:56 UTC, m4eryk commented on src/common/modules/Icons/Icons.js
> +       viewBox='0 0 50 50' width={width}
stylecode

2021-09-06 08:56 UTC, m4eryk commented on src/components/SideBarLeft/SearchTasks/SearchTasks.js
> +    if (value.length > 2 || value.length === 0) {
поиск начинаем только послее ввода 3 символов @papakapa

2021-09-06 08:56 UTC, m4eryk commented on src/helpers/debounce.js
> +export const debounce = (func, ms) => {
у дебаунса должно быть возможность отменить его

2021-09-06 09:33 UTC, maksimLyshchik commented on src/helpers/debounce.js
> +export const debounce = (func, ms) => {
исправил

2021-09-06 09:34 UTC, maksimLyshchik commented on src/common/modules/Icons/Icons.js
> +       viewBox='0 0 50 50' width={width}
исправил

2021-09-06 10:25 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +  const sortedTasks = searchTasks().sort((itemPrev, itemPres) => {
ок. понял

2021-09-06 10:25 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +      return filtredTasks.filter(task => task.value.toLowerCase().indexOf(valueSearch.toLowerCase()) > -1);
хорошо. спасибо

2021-09-06 11:31 UTC, maksimLyshchik commented on src/components/SideBarLeft/SearchTasks/SearchTasks.js
> +    if (value.length > 2 || value.length === 0) {
сделал обнуление при value.length <= 2

2021-09-06 11:32 UTC, maksimLyshchik commented on src/components/SideBarLeft/SearchTasks/SearchTasks.js
> +      const dispatchValue = () => dispatch(setSearchTasks({ value }));
перенес

2021-09-06 11:45 UTC, maksimLyshchik commented on src/common/modules/Input/Input.module.css
> +.input_search {
понял, исправил

2021-09-06 11:46 UTC, maksimLyshchik commented on src/common/modules/Input/Input.js
> +      <input className={`${s.input} ${inputType[type]}`} value={value} {...props} />
просто убрать нужно?

2021-09-06 13:34 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +      alert('Enter task');
исправил

2021-09-07 21:15 UTC, m4eryk requested changes

2021-09-07 21:15 UTC, m4eryk commented on src/components/AddTask/AddTask.jsx
> +      setTypeInput(WARNING);
оставь это пока так, и сделай это в стайленд компонентах

2021-09-07 21:15 UTC, m4eryk commented
резолви конфликты и мерджи

2021-09-08 06:56 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +      setTypeInput(WARNING);
ок, понял

2021-09-08 07:07 UTC, merged