add button state
maksimLyshchik/test-task pull request #2
Opened 2021-08-04 14:53 UTC by maksimLyshchik

2021-08-04 15:06 UTC, m4eryk requested changes

2021-08-04 15:06 UTC, m4eryk commented on src/components/TaskList/TaskList.jsx
>  import s from './TaskList.module.css';
тут тоже

2021-08-04 15:06 UTC, m4eryk commented on src/components/common/Button/Button.module.css
> +  border: 2px solid #dcdce7;
создай для цветов переменные https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2021-08-04 15:06 UTC, m4eryk commented on src/components/common/Button/Button.js
> +  const composeStyle = useMemo(() => [s.button, buttonType[type]].join(' '), [type]);
давай лучше избавимся от `useMemo` и будем интерполировать строку

2021-08-04 15:06 UTC, m4eryk commented on src/components/common/Button/Button.module.css
> +  border-radius: 5px;
используй только четные значения

2021-08-04 15:07 UTC, m4eryk commented
гитхаб так помечает отсутсвие строки в конце файла ![image](https://user-images.githubusercontent.com/47464696/128205514-e7d4c5ea-7c07-4f87-a085-b76461656dc4.png)
У каждого файла должна быть лишняя последня строка

2021-08-05 09:12 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +    console.log('event');
исправил. console.log удален

2021-08-05 09:12 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +};
добавлены пустые строки в конце файлов

2021-08-05 09:13 UTC, maksimLyshchik commented on src/components/TaskList/BlockTasks/BlockTask.jsx
> +import s from './BlockTasks.module.css';
импорты стилей перенесены в конец импортов

2021-08-05 09:13 UTC, maksimLyshchik commented on src/components/TaskList/TaskList.jsx
>  import s from './TaskList.module.css';
исправлено

2021-08-05 09:13 UTC, maksimLyshchik commented on src/components/common/Button/Button.module.css
> +  border: 2px solid #dcdce7;
добавлены переменные для цветов

2021-08-05 09:15 UTC, maksimLyshchik commented on src/components/common/Button/Button.js
> +  const composeStyle = useMemo(() => [s.button, buttonType[type]].join(' '), [type]);
исправлено. Вместо useMemo применили интерполяцию строк

2021-08-05 09:15 UTC, maksimLyshchik commented on src/components/common/Button/Button.module.css
> +  border-radius: 5px;
нечетные значения исправлены на чётные

2021-08-05 09:16 UTC, maksimLyshchik commented on .idea/inspectionProfiles/Project_Default.xml
> +    <inspection_tool class="CssUnknownProperty" enabled="true" level="WARNING" enabled_by_default="true">
в работе

2021-08-10 22:59 UTC, m4eryk commented
можно мерджить

2021-08-11 06:25 UTC, merged