Add custom checkbox
maksimLyshchik/test-task pull request #3
Opened 2021-08-06 14:56 UTC by maksimLyshchik

2021-08-10 22:58 UTC, m4eryk requested changes

2021-08-10 22:58 UTC, m4eryk commented on src/components/AddTask/AddTask.module.css
> +}
пустая строка

2021-08-10 22:58 UTC, m4eryk commented on src/components/TaskList/BlockTasks/BlockTask.jsx
> +      <Checkbox type='checkbox' onChange={handleChangeSelect} checked={selected}/>
тип не нужен

2021-08-10 22:58 UTC, m4eryk commented on src/components/TaskList/TaskList.module.css
> +.TaskList {
название  класса  должно быть не с заглавных

2021-08-10 22:58 UTC, m4eryk commented on src/components/common/Checkbox/Checkbox.module.css
> +  -webkit-user-select: none;
использовать префиксы уже давным-давно не нужно

2021-08-10 22:58 UTC, m4eryk commented on src/components/common/Checkbox/Checkbox.module.css
> +  -webkit-transform: rotate(45deg);
используй обычный `transform`

2021-08-11 06:27 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.module.css
> +}
Спасибо! ещё не всегда замечаю

2021-08-11 06:32 UTC, maksimLyshchik commented on src/components/TaskList/TaskList.module.css
> +.TaskList {
Исправил

2021-08-11 06:41 UTC, maksimLyshchik commented on src/components/common/Checkbox/Checkbox.module.css
> +  -webkit-user-select: none;
Спасибо, убрал

2021-08-11 06:42 UTC, maksimLyshchik commented on src/components/common/Checkbox/Checkbox.module.css
> +  -webkit-transform: rotate(45deg);
хорошо

2021-08-11 11:39 UTC, papakapa requested changes

2021-08-11 11:39 UTC, papakapa commented on src/components/TaskList/TaskList.module.css
> +  --task-list-br-color: #578cd5;
одинаковая константа цвета в руте для борды

2021-08-12 08:08 UTC, maksimLyshchik commented on src/components/TaskList/TaskList.module.css
> +  --task-list-br-color: #578cd5;
спасибо, исправил

2021-08-12 08:31 UTC, merged