Add button in block tasks
maksimLyshchik/test-task pull request #4
Opened 2021-08-10 16:24 UTC by maksimLyshchik

2021-08-10 22:31 UTC, m4eryk requested changes

2021-08-10 22:31 UTC, m4eryk commented on src/common/models/Button/Button.js
> +  todo: s.button_progress,
статус todo никак не относиться к кнопке

и еще rejected !== delete

2021-08-10 22:31 UTC, m4eryk commented on src/common/models/Button/Button.module.css
> +  border: 2px solid var(--brd-color);
`--brd-color`  - никак мне не говорит какого он цвета. Этот цвет вполне может использоваться не только в бордере. Давай цветам названия исходя из их цвета

2021-08-10 22:31 UTC, m4eryk commented on src/common/models/Button/Button.module.css
> +  background-color: var(--bg-color);
Переименуй все цвета

2021-08-10 22:31 UTC, m4eryk commented on src/common/models/Input/Input.js
> +  const isDisabled = type === 'disabled';
признак isDisabled не должно формироваться от типа, мы с тобой это обсуждали

2021-08-10 22:31 UTC, m4eryk commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTask({value: task, id, time: Date.now(), status: 'active'}));
Когда ты создаешь задачу она не должна быть 'active'

Используй константы для типов

2021-08-10 22:31 UTC, m4eryk commented on src/components/AddTask/AddTask.module.css
> +  display: flex;
нету пустой строки

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +  const isStatusTaskRejected = useMemo(() => {
Использовать в таком роде `useMemo` не целесообразно. Ты просто сравниваешь два примитива

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +      <Checkbox type='checkbox' onChange={handleChangeSelect} checked={selected}/>
зачем чекбоксу указывать `type='checkbox'` ?

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +        <Button color={REJECTED} onClick={handleRejectedTask} disabled={isStatusTaskRejected || isStatusTaskCompleted}>
color и тип задачи это две не совместимые сущности, не стоит их смешивать

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +        <Button color={REJECTED} onClick={handleRejectedTask} disabled={isStatusTaskRejected || isStatusTaskCompleted}>
Темплейт всегда должен быть простым, не стоит мудрить и писать вот такие штуки
```
disabled={isStatusTaskRejected || isStatusTaskCompleted}
disabled={isStatusTaskRejected || isStatusTaskCompleted || isStatusTaskTodo}
```

все это нужно вынести выше

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +        <Button color={TODO} onClick={handleTodoTask}
пройдись еще раз по стайлгайду и приведи в порядок пропсы у компонентов
https://github.com/airbnb/javascript/tree/master/react#props

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTasks.module.css
> +  background-color: #aecca3;
А этот цвет не достоин быть в константах?

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTasks.module.css
> +  background-color: #a67272;
Тут и ниже тоже обрати внимание

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTasks.module.css
> +  background-color: #dad1a9;
Ага и вот тут )

2021-08-10 22:31 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +      <div className={s.TasksList__option}>
а почему `TasksList__option` это больше на header похоже

2021-08-10 22:31 UTC, m4eryk commented on src/store/selects/actionsSelects.js
> -export const ADD_TASK = 'ADD_TASK';
selects совсем ничего не говорящее название. Использую сочетание selectedEntity

2021-08-10 22:31 UTC, m4eryk commented on src/store/selects/reducerSelects.js
> +export const selectTaskReducer = (state = [], action) => {
selectTask**Reducer**  зачем добавлять слово редюсер, он и так у тебя в сторе лежит

2021-08-10 22:31 UTC, m4eryk commented on src/store/selects/selectorSelects.js
> +);
последняя строка

2021-08-10 22:31 UTC, m4eryk commented on src/store/index.js
> +    tasks: tasksReducer,
это излишняя запись, назови нормально свои редюсеры или потом при дебаге будут проблемы

2021-08-10 22:31 UTC, m4eryk commented on src/store/tasks/actionsTasks.js
> +export const addTask = (payload) => ({type: ADD_TASK, payload});
ставь хоть какие-то энтеры между функциями, это полотно какое-то получилось

2021-08-10 22:31 UTC, m4eryk commented on src/store/tasks/reducerTasks.js
> +  }
**ты пропускаешь точки с запятыми !**

2021-08-10 22:31 UTC, m4eryk commented on src/store/tasks/selectorTasks.js
> +export const getTasks = createSelector(
раз уж выше начал, все селекторы должны называться со слова _select_

2021-08-10 22:31 UTC, m4eryk commented on src/store/selects/selectorSelects.js
> +export const getCheckedTasks = createSelector(
все селекторы должны называться со слова select

2021-08-10 22:31 UTC, m4eryk commented on src/common/models/Input/Input.module.css
> +  min-width: 500px;
min-width: 500px; - как-то многовато для инпута

2021-08-10 22:36 UTC, m4eryk commented
`models ` это в корне не верное название твоих отдельных частей проекта, то что тебе нужно это `modules`

Папка common не должна содержать в себе models. Модули живут обособлено от каких-то глобальных вещей.

2021-08-11 07:21 UTC, maksimLyshchik commented on src/common/models/Button/Button.js
> +  todo: s.button_progress,
Исправил чтобы статус rejected соответствовал стилю кнопки rejected

Не совсем понимаю на счёт статуса todo:
   у кнопки есть стиль progress и статус должен называться progress?

2021-08-11 08:02 UTC, maksimLyshchik commented on src/common/models/Button/Button.module.css
> +  background-color: var(--bg-color);
Цвета переименованы

2021-08-11 08:04 UTC, maksimLyshchik commented on src/common/models/Button/Button.module.css
> +  border: 2px solid var(--brd-color);
да, так и есть, цвета использовались в других местах и были недопонимания.
Исправил названия переменных для цветов

2021-08-11 08:09 UTC, maksimLyshchik commented on src/common/models/Input/Input.js
> +  const isDisabled = type === 'disabled';
Да, извини, исправил

2021-08-11 08:17 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTask({value: task, id, time: Date.now(), status: 'active'}));
Да, всё верно, нужно использовать константу.

Не совсем понимаю какое у неё состояние когда она просто создана
или просто создать константу ACTIVE?

2021-08-11 08:28 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +        <Button color={REJECTED} onClick={handleRejectedTask} disabled={isStatusTaskRejected || isStatusTaskCompleted}>
На счёт цветов и типов задач полностью согласен, исправил

Перемудрил, вынес из темплейта логику

2021-08-11 09:43 UTC, maksimLyshchik commented on src/common/models/Input/Input.module.css
> +  min-width: 500px;
Согласен, сделал поменьше

2021-08-11 10:02 UTC, maksimLyshchik commented on src/store/selects/selectorSelects.js
> +export const getCheckedTasks = createSelector(
Понял, хорошо

2021-08-11 10:04 UTC, maksimLyshchik commented on src/store/tasks/selectorTasks.js
> +export const getTasks = createSelector(
ок

2021-08-11 10:05 UTC, maksimLyshchik commented on src/store/tasks/reducerTasks.js
> +  }
Извини, постараюсь быть внимателнее

2021-08-11 10:06 UTC, maksimLyshchik commented on src/store/tasks/actionsTasks.js
> +export const addTask = (payload) => ({type: ADD_TASK, payload});
Понял, спасибо

2021-08-11 10:22 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.jsx
> +    dispatch(addTask({value: task, id, time: Date.now(), status: 'active'}));
Спасибо, понял

2021-08-11 11:11 UTC, maksimLyshchik commented on src/common/models/Button/Button.js
> +  todo: s.button_progress,
исправил статусы для кнопки

2021-08-11 13:10 UTC, maksimLyshchik commented on src/components/AddTask/AddTask.module.css
> +  display: flex;
Добавил

2021-08-11 13:11 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +  const isStatusTaskRejected = useMemo(() => {
Понял, исправил

2021-08-11 13:11 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +      <Checkbox type='checkbox' onChange={handleChangeSelect} checked={selected}/>
исправил

2021-08-11 13:13 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTasks.module.css
> +  background-color: #aecca3;
Определенно достоин, исправил

2021-08-11 13:13 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTasks.module.css
> +  background-color: #a67272;
исправил

2021-08-11 13:16 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +        <Button color={TODO} onClick={handleTodoTask}
В конце добавил пробел и если слишком длинная строка перенёс на новую строку
Спасибо

2021-08-11 13:17 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +      <div className={s.TasksList__option}>
Согласен, испрвил

2021-08-11 13:45 UTC, maksimLyshchik commented on src/store/selects/actionsSelects.js
> -export const ADD_TASK = 'ADD_TASK';
исправил

2021-08-11 13:45 UTC, maksimLyshchik commented on src/store/selects/reducerSelects.js
> +export const selectTaskReducer = (state = [], action) => {
исправил

2021-08-12 09:13 UTC, m4eryk requested changes

2021-08-12 09:13 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +  const isStatusButtonWarning = status === REJECTED || status === COMPLETED;
- объявляешь переменные 
 - функции 
 - рендер

2021-08-12 09:17 UTC, papakapa requested changes

2021-08-12 09:17 UTC, papakapa commented on src/common/modules/Checkbox/Checkbox.js
> +export const Checkbox = ({...props}) => {
не вижу смысла в деструктуризации здесь, как по мне лучше просто `(props) => `

2021-08-12 09:17 UTC, papakapa commented on .idea/inspectionProfiles/Project_Default.xml
> +    </inspection_tool>
не должна ли папка для idea быть в gitignore?

2021-08-12 15:40 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +  const isStatusButtonSuccess = status === REJECTED || status === COMPLETED;
Исправил

2021-08-12 15:41 UTC, maksimLyshchik commented on src/common/modules/Checkbox/Checkbox.js
> +export const Checkbox = ({...props}) => {
Исправил

2021-08-12 15:43 UTC, merged