Add filter and sort tasks
maksimLyshchik/test-task pull request #5
Opened 2021-08-12 16:21 UTC by maksimLyshchik

2021-08-13 08:36 UTC, m4eryk requested changes

2021-08-13 08:36 UTC, m4eryk commented on src/common/modules/RadioButton/RadioButton.js
> +      <label className={s.radioButton__label} >
нужно чтобы работал клик по лейблу ещу

2021-08-13 08:36 UTC, m4eryk commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +    dispatch(taskChangeTime(id));
изменение времени перевода в какой-то из статусов должно быть в экшенах которые меняют статус

2021-08-13 08:36 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +  const filterStatus = useSelector(selectFilter);
создай одну селктор фабрику, и передавай туда параметр в качестве статуса

2021-08-13 08:36 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +  const inProgressTasks = useSelector(selectInProgressTasks);
это позволит избавиться тебе от копипаста

2021-08-13 09:14 UTC, papakapa requested changes

2021-08-13 09:14 UTC, papakapa commented on src/components/TasksList/TasksList.jsx
> +    } else if (itemPrev.timeChange < itemPres.timeChange) {
тут тоже

2021-08-13 10:02 UTC, maksimLyshchik commented on src/common/modules/RadioButton/RadioButton.js
> +      <label className={s.radioButton__label} >
Вложил input в label

2021-08-13 10:03 UTC, maksimLyshchik commented on src/common/modules/RadioButton/RadioButton.js
> +export const RadioButton = ({...props}) => {
понял, спасибо

2021-08-13 10:07 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    } else if (conditionsFilter === IN_PROGRESS) {
согласен

2021-08-13 10:07 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    } else if (itemPrev.timeChange < itemPres.timeChange) {
да, спасибо

2021-08-13 10:08 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
>    const isStatusButtonWarning = status === REJECTED || status === COMPLETED;
да, с предыдущего pr понял, спасибо

2021-08-13 10:40 UTC, maksimLyshchik commented on src/components/TasksList/BlockTasks/BlockTask.jsx
> +    dispatch(taskChangeTime(id));
да, лишние действия делал
исправил, спасибо

2021-08-13 10:41 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +  const filterStatus = useSelector(selectFilter);
Исправил, не уверен, что верно

2021-08-16 14:45 UTC, m4eryk requested changes

2021-08-16 14:45 UTC, m4eryk commented on src/components/SideBar/TasksFilter/TasksFilter.js
> +import s from './TasksFilter.module.css';
следи за порядком импротов

2021-08-16 14:45 UTC, m4eryk commented on src/components/TasksList/BlockTask/BlockTask.module.css
> +}
пустая строка

2021-08-16 14:45 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +    const changeSortingRule = sortingRule === ASCENDING ? DESCENDING : ASCENDING;
не совсем понимаю смысл этой проверки, ты же можешь сразу передать `sortingRule `

2021-08-16 15:34 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    const changeSortingRule = sortingRule === ASCENDING ? DESCENDING : ASCENDING;
значение sortingRule берём из стейта, здесь я меняю его на противоположное значение и перезаписываю уже измененное

2021-08-16 15:34 UTC, maksimLyshchik commented on src/components/TasksList/BlockTask/BlockTask.module.css
> +}
Извини, кажется следил за этим

2021-08-16 15:35 UTC, maksimLyshchik commented on src/components/SideBar/TasksFilter/TasksFilter.js
> +import s from './TasksFilter.module.css';
да, спасибо, пропустил

2021-08-16 15:37 UTC, maksimLyshchik commented on src/common/modules/RadioButton/RadioButton.module.css
> +  margin: 0 5px 0 0;
да, согласен

2021-08-16 15:38 UTC, maksimLyshchik commented on src/common/modules/RadioButton/RadioButton.module.css
> +  margin-bottom: 5px;
спасибо, ещё не привык, постараюсь внимательней писать

2021-08-16 15:38 UTC, maksimLyshchik commented on src/common/modules/RadioButton/RadioButton.module.css
> +}
да, спасибо

2021-08-16 15:39 UTC, maksimLyshchik commented on src/common/modules/RadioButton/RadioButton.js
> +      <input className={`${s.radioButton__input} ${radioButtonColors[type]}`} type='radio' name={name} value={value} onClick={onClick} {...props}/>
полностью согласен

2021-08-16 15:41 UTC, maksimLyshchik commented on src/common/modules/Icons/sprite.svg
> +    <symbol id='arrow_down' viewBox="0 0 24 24">
хорошо, спасибо

2021-08-16 15:43 UTC, maksimLyshchik commented on src/App.js
> +    <div className={s.app_section} >
понял, спасибо

2021-08-17 07:45 UTC, m4eryk commented
от меня ок 
@papakapa, посмотри, если все ок - давай добро на мердж

2021-08-17 15:08 UTC, merged