Add edditing multiple tasks
maksimLyshchik/test-task pull request #6
Opened 2021-08-17 07:06 UTC by maksimLyshchik

2021-08-17 07:49 UTC, m4eryk requested changes

2021-08-17 07:49 UTC, m4eryk commented on src/components/SideBarRight/EditorTasks/EditorTasks.js
> +    markTasksId.map(id => dispatch(rejectedTask(id)));
если тебе нужно перебрать массив, используй forEach.

2021-08-17 07:49 UTC, m4eryk commented on src/components/SideBarRight/EditorTasks/EditorTasks.js
> +    markTasksId.map(id => dispatch(setSelectTask({[id]: false})));
Зачем два раза перебирать массив, если ты можешь это все сделать за раз

2021-08-17 07:49 UTC, m4eryk commented on src/components/SideBarRight/EditorTasks/EditorTasks.js
> +    markTasksId.map(id => dispatch(completedTask(id)));
Тут и ниже все также нужно поправить

2021-08-17 08:18 UTC, maksimLyshchik commented on src/components/SideBarRight/EditorTasks/EditorTasks.js
> +    markTasksId.map(id => dispatch(rejectedTask(id)));
хорошо, спасибо

2021-08-17 08:18 UTC, maksimLyshchik commented on src/components/SideBarRight/EditorTasks/EditorTasks.js
> +    markTasksId.map(id => dispatch(setSelectTask({[id]: false})));
согласен, исправил

2021-08-17 08:18 UTC, maksimLyshchik commented on src/components/SideBarRight/EditorTasks/EditorTasks.js
> +    markTasksId.map(id => dispatch(completedTask(id)));
исправил

2021-08-18 08:16 UTC, papakapa requested changes

2021-08-18 08:16 UTC, papakapa commented on src/components/SideBarLeft/EditorTasks/EditorTasks.js
> +
лишние строки

2021-08-18 08:16 UTC, papakapa commented on src/components/SideBarLeft/SideBarLeft.js
> +  const handleSideBarPosition = useCallback( () => {
лишний пробел

2021-08-18 08:16 UTC, papakapa commented on src/components/TasksList/TasksList.jsx
> +    filtredTasks.map(item => item.id).forEach(key => selectAll[key] = checked);
ненужное использовние map, можно просто пройтись по filteredTasks используя forEach и деструктуризируя id

2021-08-18 08:16 UTC, papakapa commented on src/components/TasksList/TasksList.jsx
> +    return Boolean(length) && length === Object.values(selectedTasks).filter(value => value).length;
если нужна только длина, то лучше взять ее из filteredTasks и избавиться от taskIds

2021-08-18 08:16 UTC, papakapa commented on src/store/selectedEntity/selectorSelects.js
> +export const selectMarkedTask = store => Object.entries(store.selects).filter(item => item[1] === true).map(item => item[0]);
тоже лишняя проверка на true, просто `filter(item => item[1])`

2021-08-18 08:37 UTC, maksimLyshchik commented on src/store/selectedEntity/selectorSelects.js
> +export const selectMarkedTask = store => Object.entries(store.selects).filter(item => item[1] === true).map(item => item[0]);
Да, спасибо

2021-08-18 08:39 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    return Boolean(length) && length === Object.values(selectedTasks).filter(value => value).length;
Хорошо, спасибо

2021-08-18 08:51 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    filtredTasks.map(item => item.id).forEach(key => selectAll[key] = checked);
да, спасибо, так вышло проще

2021-08-18 08:52 UTC, maksimLyshchik commented on src/components/SideBarLeft/SideBarLeft.js
> +  const handleSideBarPosition = useCallback( () => {
точно

2021-08-18 08:53 UTC, maksimLyshchik commented on src/components/SideBarLeft/EditorTasks/EditorTasks.js
> +
да, спасибо

2021-08-18 08:55 UTC, maksimLyshchik commented on src/components/SideBarLeft/EditorTasks/EditorTasks.js
> +    const editorPosition = Object.values(selectedTasks).filter(item => item === true).length;
да, понял

2021-08-18 08:55 UTC, maksimLyshchik commented on src/components/SideBarLeft/EditorTasks/EditorTasks.js
> +  const handleEditorPosition = useMemo( () => {
убрал

2021-08-19 09:00 UTC, papakapa commented on src/components/EditorTasks/EditorTasks.js
> +    return isVisebled && s.collapsed;
можно упростить в одну строку 
```suggestion
    const handleEditorPosition = useMemo(() => isVisebled && s.collapsed, [selectedTasks]);
```

2021-08-19 09:13 UTC, maksimLyshchik commented on src/components/EditorTasks/EditorTasks.js
> +    return isVisebled && s.collapsed;
Спасибо, полностью согласен

2021-08-19 09:52 UTC, papakapa approved these changes

2021-08-19 16:37 UTC, merged