Add time change tasks
maksimLyshchik/test-task pull request #7
Opened 2021-08-19 07:40 UTC by maksimLyshchik

2021-08-20 08:28 UTC, papakapa requested changes

2021-08-20 08:28 UTC, papakapa commented on src/components/TasksList/TasksList.jsx
> +    console.log(filtredTasks);
ненужный лог

2021-08-20 08:29 UTC, m4eryk requested changes

2021-08-20 08:29 UTC, m4eryk commented on src/components/SideBarLeft/SideBarLeft.js
> +        {sideBarPosition === s.collapsed && <span>Filter</span>}
такого не должно быть в темплейтах, выноси флаг выше

2021-08-20 08:29 UTC, m4eryk commented on src/components/TasksList/TasksList.jsx
> +    console.log(filtredTasks);
console.log(

2021-08-20 08:29 UTC, m4eryk commented on src/helpers/getDateNow.js
> +  const formatTime = new Date(time).toLocaleTimeString('en-GB',{ hour12: false });
codestyle

2021-08-20 08:57 UTC, maksimLyshchik commented on src/helpers/getDateNow.js
> +  const formatTime = new Date(time).toLocaleTimeString('en-GB',{ hour12: false });
исправил, спасибо

2021-08-20 08:57 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    console.log(filtredTasks);
извини, не заметил

2021-08-20 08:57 UTC, maksimLyshchik commented on src/components/SideBarLeft/SideBarLeft.js
> +        {sideBarPosition === s.collapsed && <span>Filter</span>}
понял, вынес

2021-08-20 08:58 UTC, maksimLyshchik commented on src/components/TasksList/TasksList.jsx
> +    console.log(filtredTasks);
да, спасибо, убрал

2021-08-20 10:33 UTC, papakapa approved these changes

2021-08-20 12:55 UTC, papakapa requested changes
![image](https://user-images.githubusercontent.com/58229984/130236261-0548a987-4c77-4c75-915f-dd1db34df8a0.png)

таких предупреждений обыно не должно быть

2021-08-23 12:27 UTC, papakapa approved these changes

2021-08-23 12:28 UTC, merged